CREATE TABLE [Patient] (
  [Id] INTEGER PRIMARY KEY, 
  [Name] VARCHAR, 
  [Registry] VARCHAR NOT NULL, 
  [BirthDate] DATE, 
  [Gender] CHAR(2), 
  [OriginationId] INTEGER, 
  [InternmentDate] DATETIME, 
  [InternmentTypeId] INTEGER, 
  [IsReInternment] BOOLEAN, 
  [IsReInternment48h] BOOLEAN, 
  [DiagnosticId] INTEGER, 
  [Apache2] INTEGER, 
  [SAPS3] INTEGER, 
  [DischargeDate] DATE, 
  [DischargeReasonId] INTEGER, 
  [VMDuration] INTEGER, 
  [HasICC] BOOLEAN, 
  [HasIRC] BOOLEAN, 
  [HasDCPF] BOOLEAN, 
  [HasDPOC] BOOLEAN, 
  [HasHematologyTumor] BOOLEAN, 
  [HasLocoregionalTumor] BOOLEAN, 
  [HasMetastasis] BOOLEAN, 
  [HasHAS] BOOLEAN, 
  [HasDM] BOOLEAN, 
  [HasPreviousIAM] BOOLEAN, 
  [HasAVC] BOOLEAN, 
  [HasVisualDeficit] BOOLEAN, 
  [HasAuditoryDeficit] BOOLEAN, 
  [HasDementia] BOOLEAN, 
  [HasAlcoholism] BOOLEAN, 
  [HasSmoking] BOOLEAN, 
  [HasImmunoSuppression] BOOLEAN, 
  [HasSIDA] BOOLEAN, 
  [HasRheumaticDisorder] BOOLEAN, 
  [HasPsychiatricDisorder] BOOLEAN);


CREATE TABLE [PatientEvaluation] (
  [Id] INTEGER, 
  [PatientId] INTEGER, 
  [Date] DATE, 
  [RASS] INTEGER, 
  [DeliriumId] INTEGER, 
  [VentilationId] INTEGER, 
  [SedationId] INTEGER);


