/****************** GENERATORS ********************/

CREATE GENERATOR GEN_CATEGORIES_ID;
CREATE GENERATOR GEN_CONTACTS_ID;
CREATE GENERATOR GEN_PHONES_ID;

/******************** TABLES **********************/

CREATE TABLE CATEGORIES
(
  ID integer NOT NULL,
  NAME varchar(300),
  CONSTRAINT INTEG_4 PRIMARY KEY (ID)
);
CREATE TABLE CONTACTS
(
  ID integer NOT NULL,
  CATEGORYID integer,
  NAME varchar(300),
  CONSTRAINT INTEG_6 PRIMARY KEY (ID)
);
CREATE TABLE PHONES
(
  ID integer NOT NULL,
  CONTACTID integer,
  NUMBER varchar(100),
  CONSTRAINT INTEG_9 PRIMARY KEY (ID)
);

/******************** TRIGGERS ********************/

SET TERM ^ ;
CREATE TRIGGER CATEGORIES_BI FOR CATEGORIES ACTIVE
BEFORE insert POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CATEGORIES_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CATEGORIES_ID, 0);
    if (tmp < new.ID) then
      tmp = GEN_ID(GEN_CATEGORIES_ID, new.ID-tmp);
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER CONTACTS_BI FOR CONTACTS ACTIVE
BEFORE insert POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CONTACTS_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_CONTACTS_ID, 0);
    if (tmp < new.ID) then
      tmp = GEN_ID(GEN_CONTACTS_ID, new.ID-tmp);
  END
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER PHONES_BI FOR PHONES ACTIVE
BEFORE insert POSITION 0
AS
DECLARE VARIABLE tmp DECIMAL(18,0);
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PHONES_ID, 1);
  ELSE
  BEGIN
    tmp = GEN_ID(GEN_PHONES_ID, 0);
    if (tmp < new.ID) then
      tmp = GEN_ID(GEN_PHONES_ID, new.ID-tmp);
  END
END^
SET TERM ; ^

ALTER TABLE CONTACTS ADD CONSTRAINT INTEG_7
  FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES (ID) ON DELETE SET NULL;
ALTER TABLE PHONES ADD CONSTRAINT INTEG_10
  FOREIGN KEY (CONTACTID) REFERENCES CONTACTS (ID) ON DELETE CASCADE;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CATEGORIES TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON CONTACTS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PHONES TO  SYSDBA WITH GRANT OPTION;

